from typing import Protocol
from .models import DriverProfile

class Embedder(Protocol):
    def embed(self, text: str) -> list[float]: ...

class VectorStore(Protocol):
    def search(self, query: str, k: int): ...

class ChatModel(Protocol):
    def complete_json(self, system: str, user: str) -> dict: ...

class ProfileRepository(Protocol):
    def load(self) -> DriverProfile: ...
    def save(self, profile: DriverProfile) -> None: ...
