def is_risky_frame(frame_safety) -> bool:
    return (
        bool(frame_safety.unsafe_ttc)
        or bool(frame_safety.unsafe_drac)
        or bool(frame_safety.unsafe_dcpa)
        or bool(frame_safety.unsafe_future_distance)
        or (
            frame_safety.physical_risk_index is not None
            and frame_safety.physical_risk_index >= 0.35
        )
    )


def should_call_llm(policy: str, frame_pos: int, frame_safety, stride: int = 5) -> bool:
    policy = (policy or "always").lower()
    stride = max(1, int(stride or 1))

    if policy == "always":
        return True

    if policy == "stride":
        return frame_pos % stride == 0

    if policy == "risk_only":
        return is_risky_frame(frame_safety)

    if policy == "hybrid":
        return is_risky_frame(frame_safety) or frame_pos % stride == 0

    return True


def fallback_decision_from_physics(frame_safety) -> dict:
    risky = is_risky_frame(frame_safety)

    if frame_safety.physical_risk_index is not None:
        if frame_safety.physical_risk_index >= 0.65:
            level = "high"
        elif frame_safety.physical_risk_index >= 0.35:
            level = "medium"
        else:
            level = "low"
    else:
        level = "medium" if risky else "low"

    return {
        "is_potential_violation": risky,
        "risk_level": level,
        "recommended_action": "保持安全距离并降低风险暴露" if risky else "保持当前策略",
        "reason": "Generated by physics-based fallback decision.",
        "confidence": 0.5,
        "source": "physics_fallback",
    }